name: Flutter CI

on:
  push:
    branches: [ "main", "frontend", "frontend-dev" ]
  pull_request:
    branches: [ "main", "frontend", "frontend-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: flutter pub get

    # - name: Analyze
    #   run: flutter analyze

    - name: Run tests
      run: flutter test
